# Signal generation interface for StrategyFramework

using Planar.Engine.TimeTicks
using Planar.Engine.TimeTicks: Dates
using Planar

"""
    SignalGenerator

Abstract type for signal generation implementations.
All signal generators must implement the required methods:
- `generate_buy_signal(sg, s, ii, ats)`
- `generate_sell_signal(sg, s, ii, ats)`

Optional methods with default implementations:
- `should_trade(sg, s, ii, ats)` - returns true by default
- `get_signal_lifetime(sg)` - returns 0.2 by default
"""
abstract type SignalGenerator end

"""
    SignalState

Mutable struct to track signal state and lifetime management.
"""
@kwdef mutable struct SignalState
    last_buy_signal::DateTime = DateTime(0)
    last_sell_signal::DateTime = DateTime(0)
    buy_signal_active::Bool = false
    sell_signal_active::Bool = false
    signal_lifetime::Float64 = 0.2
    signal_count::Int = 0
    last_signal_type::Symbol = :none
end

# Required methods for signal generators
"""
    generate_buy_signal(sg::SignalGenerator, s::SC, ii, ats)

Generate a buy signal for the given asset and timestamp.
Must be implemented by all signal generators.

# Arguments
- `sg::SignalGenerator`: The signal generator instance
- `s::SC`: The strategy instance
- `ii`: Instrument instance
- `ats`: Available timestamp

# Returns
- `Bool`: true if a buy signal is generated, false otherwise
"""
function generate_buy_signal(sg::SignalGenerator, s::SC, ii, ats)
    error("generate_buy_signal must be implemented by $(typeof(sg))")
end

"""
    generate_sell_signal(sg::SignalGenerator, s::SC, ii, ats)

Generate a sell signal for the given asset and timestamp.
Must be implemented by all signal generators.

# Arguments
- `sg::SignalGenerator`: The signal generator instance
- `s::SC`: The strategy instance
- `ii`: Instrument instance
- `ats`: Available timestamp

# Returns
- `Bool`: true if a sell signal is generated, false otherwise
"""
function generate_sell_signal(sg::SignalGenerator, s::SC, ii, ats)
    error("generate_sell_signal must be implemented by $(typeof(sg))")
end

# Optional methods with default implementations
"""
    should_trade(sg::SignalGenerator, s::SC, ii, ats)

Determine if trading should be allowed for the given asset and timestamp.
Default implementation always returns true.

# Arguments
- `sg::SignalGenerator`: The signal generator instance
- `s::SC`: The strategy instance
- `ii`: Instrument instance
- `ats`: Available timestamp

# Returns
- `Bool`: true if trading is allowed, false otherwise
"""
function should_trade(sg::SignalGenerator, s::SC, ii, ats)
    true  # Default: always allow trading
end

"""
    get_signal_lifetime(sg::SignalGenerator)

Get the lifetime of signals generated by this signal generator.
Default implementation returns 0.2 seconds.

# Arguments
- `sg::SignalGenerator`: The signal generator instance

# Returns
- `Float64`: Signal lifetime in seconds
"""
function get_signal_lifetime(sg::SignalGenerator)
    0.2  # Default signal lifetime
end