name = "BBWithOpt"
uuid = "49e7d402-6e80-11ee-3ea0-03e999f86b56"
version = "0.1.0"
authors = ["zbc"]

[deps]
OnlineTechnicalIndicators = "dc2d07fb-478f-4566-8417-81bb3e5a7af1"
PlanarOptim = "01937fd2-c099-442f-ae89-75fa208aad36"
Planar = "646fb1a4-6797-441d-ad18-3bdbde2eb86b"
PlanarCore = "a475c859-e357-4be2-a5e3-43038ab4b158"

[sources]
PlanarCore = {path = "../../../PlanarCore"}
PlanarOptim = {path = "../../../PlanarOptim"}
Planar = {path = "../../../Planar"}

[compat]
OnlineTechnicalIndicators = "0.1.2"

[strategy]
margin = "Isolated"
mode = "Sim"
